### ISSUE TITLE
Revision-detection code is wrong

### ISSUE THREAD

**Issue by lurch** [romilly/quick2wire-python-api#14]
I think the code in https://github.com/quick2wire/quick2wire-python-api/blob/master/src/quick2wire/board_revision.py should be checking for:
in ['2','3']
rather than:
in ['1','2']

References:
http://www.raspberrypi.org/archives/1929
http://code.google.com/p/raspberry-gpio-python/source/browse/source/cpuinfo.c
http://www.andrewscheller.co.uk/adc_demo.py

**Comment by romilly** [comment]
You're right. Now corrected. Thanks.
