### ISSUE TITLE
Automatically unexport pins

### ISSUE THREAD

**Issue by odiroot** [romilly/quick2wire-python-api#2]
I think it'd be useful to automatically unexport previously used pins.
Since a pin is in your case a normal Python object of `Pin` class its `__del__`  method 
can be used to perform this task. This way pin will be freed during object's destruction.

Something along these lines;

```
 class Pin(object):
     # [...]
     def __del__(self):
         self.unexport()
```

There is obviously an issue when sb creates multiple instances of `Pin` objects referencing the same hardware pin.

**Comment by npryce** [comment]
There's no clean solution to the issue you mention at the end there.  Instead, use the 'exported' context manager with the with statement to automatically control the scope of the pin's exportedness.

For example:

```
from quick2wire.gpio import Pin, exported
from time import sleep

with exported(Pin(15)) as pin:
    pin.value = 1
    sleep(10)
    pin.value = 0

# After the with statement the pin has been unexported again
```
