### ISSUE TITLE
I2C does not work with Kernel 3.6 on Raspbian

### ISSUE THREAD

**Issue by npryce** [romilly/quick2wire-python-api#20]
If you upgrade Raspbian to kernel 3.6 with rpi-update, the I2C API fails with the following error:

```
File "/home/pi/quick2wire-python-api/src/quick2wire/i2c.py", line 74, in transaction
    ioctl(self.fd, I2C_RDWR, addressof(ioctl_arg))
OverflowError: Python int too large to convert to C long
```

**Comment by npryce** [comment]
Not sure what the issue is.  It could be an incompatible change in the i2c-dev ioctl API between 3.2 and 3.6.

Or the kernel installed by 3.6 has been compiled by a different compiler or different compile options, making the ABI incompatible.

Or, our ctypes declarations are incorrect, making them brittle w.r.t. kernel changes.

**Comment by npryce** [comment]
I believe its fixed.  I've pushed the fix to GitHub but have not yet tried it on the 3.2 kernel.

If anyone is brave enough to pull the latest changes and try it, please report your experience in the comments. Thanks.

**Comment by ghost** [comment]
Works for me - tested on kernel versions 3.2.27+ #307 and 3.6.11+ #352

**Comment by npryce** [comment]
Glad to hear it.  Thanks for letting us know.  I'm just rolling back to 3.2.27+ myself and if it works for me too, I'll mark the issue as closed.

**Comment by npryce** [comment]
It passes the MCP23017 loopback tests on kernels 3.2.27+ and 3.6.11+, so closing.

**Comment by VitorPS** [comment]
Hello npryce, first of all thank you for writing these libraries! I'm communicating between a raspberry (raspbian kernel 3.6.11+) and two devices (MAX32855 and MCP4822) through quick2wire-python-api-0.0.0.2.
My application keeps "talking" to these devices each 2 seconds, and usually works fine for days, but sometimes it returns the following error:
"File "/home/pi/quick2wire-python-api/src/quick2wire/spi.py", line 64, in transaction
    ioctl(self.fd, SPI_IOC_MESSAGE(transfer_count), addressof(ioctl_arg))
OverflowError: Python int too large to convert to C long"
If I restart my application, it runs smoothly again.
Any hints on how to solve this? Maybe a workaround would be downgrading the kernel version, but i'd rather solve this on kernel 3.6.11.

Thanks a lot!
