### ISSUE TITLE
I2C API truncates multi-byte reads

### ISSUE THREAD

**Issue by omerk** [romilly/quick2wire-python-api#5]
Hi,

I can't seem to get multi-byte reads working, which may be a bug or simply a case of me not using things properly.

Here's what I am trying to do:

```
Python 3.2.3 (default, Jun 15 2012, 19:45:57) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import quick2wire.i2c as i2c
>>> with i2c.I2CBus() as bus:
...   bus.transaction(i2c.write_bytes(0x48, 0x01, 0b01000000, 0b10000011))
...   result = bus.transaction(i2c.write_bytes(0x48, 0x00), i2c.read(0x48, 2))
...  
[]
>>> result
[b'D']
>>> print("0x%02x" % result[0][0])
0x44
>>> print("0x%02x" % result[1][0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

It certainly is working on the hardware side of things, here's the logic analyzer capture of data going in and out of the device: http://img850.imageshack.us/img850/9694/logicc.png

Any recommendations?

Thanks.

**Comment by npryce** [comment]
The last line should be print("0x%02x" % result[0][1])  (getting the second byte of the first and only read result)

But I can see that the returned buffer is only one byte long.

I'll look into it.

**Comment by npryce** [comment]
Yes, there was a bug in the way the API converted C buffers to Python bytes objects.  I've checked in a fix, so if you do a git pull you should see things start working.

**Comment by omerk** [comment]
Confirmed working, thanks for the quick fix.
