### ISSUE TITLE
ImportError: No module named quick2wire.i2c

### ISSUE THREAD

**Issue by rudi48** [romilly/quick2wire-python-api#52]
Hello,
While testing a Wireless Optical Mouse & Keyboard X1800 from company RAPOO I have seen, that is does not work reliable under Raspbian version 2013-02-09. An update to Raspbian version 2014-01-07 solved the problem.
Now I got another problem, wobbulator.py throws an error message:
**ImportError: No module names quickwire.i2c**
When I run the command **sudo env** I saw, that the environment variable **PYTHONPATH** from the file "/home/pi/.profile" is no longer there, but it is there when I just type **env**.
My solution to the problem was to insert in wobbulator.py:

```
import sys
# setup the path according to your local installation
sys.path.append('/home/pi/Install/quick2wire-python-api-master')
#import quick2wire i2c module
import quick2wire.i2c as i2c
```

Is there maybe a better solution?
Regards, Rudolf DL5FA

**Comment by rudi48** [comment]
In the meantime I found an easier solution.
In IDLE3 you can see in the menu **File/Path Browser** which paths are already used.
From that I selected **/usr/local/lib/python3.2/dist-packages**, so

```
copy folder quick2wire-python-api-master/quick2wire to /usr/local/lib/python3.2/dist-packages/
```

In this way you no longer need the PYTHONPATH environment variable, and can use **sudo**.
Regards, Rudolf DL5FA

**Comment by Givy** [comment]
Hi,

I have has problem with Quick2Wire fro day one.  I Understand it is dead, but I still have to finish installing it.  I don't have a "quick2wire-python-api-master".  My path stops at "/git/quick2wire-python-api/".

I also can't do "from quick2wire.i2c import I2CMaster" and get below errors.  Where have I gone wrong with this?  Any assistance is appreciated.

> > > from quick2wire.i2c import I2CMaster
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named quick2wire.i2c
